image:https://img.shields.io/:license-apache-blue.svg[License,link=https://raw.githubusercontent.com/averemee-si/ora2iceberg/refs/heads/main/LICENSE]
image:https://img.shields.io/maven-central/v/solutions.a2.oracle.iceberg/ora2iceberg[link=https://search.maven.org/artifact/solutions.a2.oracle.iceberg/ora2iceberg/0.8.1.7/jar?eh=]

= ora2iceberg Data Pipe

== 1. What is Ora2Iceberg?
Ora2Iceberg is your go-to tool for simplifying data migration! It seamlessly transfers Oracle tables and views into Iceberg structures across various data lakes and warehouses—whether cloud-based or on-premises. Supporting a wide range of storage systems, including S3-compatible, HDFS, and local files, it integrates effortlessly with all Iceberg-compatible catalogs. This includes JDBC connections to popular free databases like PostgreSQL and MySQL, making complex Hadoop setups or Spark/Hive unnecessary. Seriously, who wants more Hadoop headaches?

=== Who Benefits from Ora2Iceberg?
* Data Engineers: Effortlessly migrate from legacy Oracle databases to modern systems (finally, something less painful than Mondays!).
* Cloud Architects: Enable cost-effective and scalable data lakes like AWS Glue and S3Tables.
* Database Administrators: Simplify schema conversions and data type mappings without breaking a sweat.
* Analytics Teams: Unlock high-performance querying with Iceberg’s partitioning and indexing. It’s like upgrading from a bicycle to a sports car.

=== Key Features
* Multi-Catalog Support: Compatible with Glue, Hive, S3Tables, and more.
* Customizable Data Mappings: Override Oracle-to-Iceberg type mappings with ease.
* Partitioning Options: Optimize table performance with advanced partitioning strategies.
* Flexible Upload Modes: Full, incremental, and future merge upload modes.
* Security Compliance: Validate dependencies for secure builds—because nobody likes surprises in production.

== 2. Getting Started
=== Prerequisites
==== Environment Setup:
* Install Java (JDK 11 or later).
==== Supported Iceberg Catalogs:
* REST, JDBC, Hadoop, Hive, Nessie, Glue, S3Tables, DynamoDB.

=== Installation
==== 1. Clone the repository
----
git clone https://github.com/a2solutions/ora2iceberg.git
----

==== 2. Navigate to the project directory:
----
cd ora2iceberg
----

==== 3. Build the project:
** On Linux/Unix:
----
gradle clean build
----
** On Windows:
----
./gradlew clean build
----
==== 4. Run the tool:
----
java -jar build/libs/ora2iceberg.jar
----
=== Optional: Validating Secure Dependencies
Run the following to ensure all dependency libraries are secure:
----
gradle dependencyCheckAnalyze
----

== 3. Basic Usage
=== Common assumptions:
The machine on which you run ora2Iceberg can be: 

* Remote or local to the source Oracle database;
* Remote or local to the destination catalogs;
* Remote to the destination storage if it supports the network access (S3-compatible, Hadoop, SnowFlake);
* Local to the destination storage if copying to the plain local file system.

The tool can be run on Linux or Windows in any shell of your choice capable of running Java 11 and later (the popular free JREs like Corretto and Temurin are fully supported).

=== Scenario 1: Copying the table to AWS S3 Storage and using AWS Glue as catalog.
This scenario implies copying the Oracle tables to the general AWS S3 storage, that can be further accessed by AWS analytical tools.

==== Prerequisites
* Configure the S3 storage bucket (specified as iceberg-warehouse in the below example)
* Configure and save the AWS access key pair according to https://docs.aws.amazon.com/IAM/latest/UserGuide/security-creds-programmatic-access.html 
* Set the following environment variables in your shell:
** AWS_REGION to the region of your bucket;
** AWS_ACCESS_KEY_ID to your access key ID;
** AWS_SECRET_ACCESS_KEY to the secret access key.











---- 
gradle clean build
----
 
The generated jar files can be found at: `build/libs/`.

An uber jar containing the library and all its relocated dependencies can also be built. Use this command: 
----
gradle clean shadowJar
----

The generated uber jar file can also be found at: `build/libs/`.
 
=== Validating secure dependencies
To ensure no security vulnerabilities in the dependency libraries, run the following.
----
gradle dependencyCheckAnalyze
----

=== Source Connection Parameters

[cols="1,2,4,3", options="header"]
|===
| Short | Long | Explanation | Example

| `-j` | `--source-jdbc-url` | Oracle JDBC URL for the source connection. This parameter is required. | `jdbc:oracle:thin:@localhost:1521:xe`
| `-u` | `--source-user` | Oracle username for the source connection. | `system`
| `-p` | `--source-password` | Password for the source Oracle connection. | `password123`
| `-s` | `--source-schema` | Source schema name. If not specified, the value of `<source-user>` is used. | `HR`
| `-o` | `--source-object` | Name of the source table, view, or SQL `SELECT` query. *SQL `SELECT` is not implemented yet.* | `employees` or `SELECT * FROM employees WHERE department_id = 10`
| `-w` | `--where-clause` | Optional `WHERE` clause for the `<source-object>`. Valid only if `<source-object>` points to a table or view. | `WHERE salary > 50000`
|===

=== Iceberg Destination Parameters

[cols="1,2,4,3", options="header"]
|===
| Short | Long | Explanation | Example

| `-T` | `--iceberg-catalog-type` | Type of Iceberg catalog. Can be predefined (e.g., REST, JDBC, HADOOP) or a fully qualified class name. | `REST`
| `-C` | `--iceberg-catalog` | Name of the Apache Iceberg catalog. | `MyCatalog`
| `-U` | `--iceberg-catalog-uri` | URI for the Apache Iceberg catalog. | `http://localhost:8080`
| `-H` | `--iceberg-warehouse` | Location of the Apache Iceberg warehouse. | `/path/to/warehouse`
| `-N` | `--iceberg-namespace` | Namespace for the Iceberg catalog. Defaults to the source schema. | `db_namespace`
| `-t` | `--iceberg-table` | Name of the destination Iceberg table. Defaults to the source object name for tables/views. | `iceberg_table_name`
| `-P` | `--iceberg-partition` | Partitioning definitions for the Iceberg table. | `columnName=YEAR` or `columnName=BUCKET,10`
| `-L` | `--upload-mode` | Upload mode: `full`, `incremental`, or `merge`. *Merge is not implemented yet.* | `full`
| `-R` | `--iceberg-catalog-properties` | Additional properties for Apache Iceberg catalog implementation | `-Rs3.endpoint=http://ozone.companyname.com:9878/`
|===

=== Additional Options

[cols="1,2,4,3", options="header"]
|===
| Short | Long | Explanation | Example

| `-f` | `--auto-infer-types` | Automatically infer numeric types (e.g., BIGINT vs NUMERIC). *Not implemented yet.* | `-f`
| `-d` | `--default-number-type` | Default numeric precision/scale for ambiguous `NUMBER` columns. Defaults to `decimal(38,10)`. | `decimal(10,2)`
| `-m` | `--data-type-map` | Custom mappings from source data types to Iceberg types. | `"COLUMN_NAME:NUMBER=integer; PATTERN%:NUMBER=decimal(20,0)"`
|===


=== More Information

For more details, documentation, and updates, visit the official website:

https://ora2iceberg.app/

== Authors
**Aleksej Veremeev** - *Initial work* - http://a2-solutions.eu/[A2 Rešitve d.o.o.]

== License

This project is licensed under the Apache-2.0 License.

